<Project>
  <!-- iPlus settings and overrides -->
  <Import Condition="'$(UseAvaloniaFork)' == 'True'" Project="../iPlus/Directory.Packages.props" />
  <!-- End iPlus settings and overrides -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Condition="'$(UseAvaloniaFork)' != 'True'">
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.242" />
  </ItemGroup>
</Project>
