<Project>
  <!-- iPlus settings and overrides -->
  <Import Condition="'$(UseAvaloniaFork)' == 'True'" Project="../../iPlus/build/Avalonia.Build.props" />
  <!-- End iPlus settings and overrides -->

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <Features>strict</Features>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <AvaloniaVersion Condition="'$(UseAvaloniaFork)' != 'True'">12.0.0</AvaloniaVersion>
    <AvaloniaSampleVersion Condition="'$(UseAvaloniaFork)' != 'True'">12.1.1</AvaloniaSampleVersion>

    <!-- Signing configuration -->
    <SignAssembly>false</SignAssembly>
    <PublicSign Condition="'$(SignAssembly)' == 'true'">true</PublicSign>
    <AvaloniaPublicKey></AvaloniaPublicKey>

    <!-- CS0067: The event '' is never used -->
    <!-- NU1900: Error occurred while getting package vulnerability data -->
    <!-- NU5104: A stable release of a package should not have a prerelease dependency -->
    <!-- NU1801: Unable to load the service index (XPF) -->
    <NoWarn>$(NoWarn);CS0067;NU1900;NU5104;NU1902;NU1903;NU1801</NoWarn>

    <RepoRoot Condition="'$(RepoRoot)' == ''">$(MSBuildThisFileDirectory)</RepoRoot>
    <PackageOutputPath>$(RepoRoot)\artifacts\packages</PackageOutputPath>
  </PropertyGroup>

</Project>
