<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0;net10.0-android;net10.0-browser</TargetFrameworks>

    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Avalonia.Controls</RootNamespace>
    <WarningsAsErrors>$(WarningsAsErrors);CA1420;CA1421;</WarningsAsErrors>
    <CopyLocalLockFileAssemblies Condition="'$(ILMergeBuild)' == 'true'">true</CopyLocalLockFileAssemblies>
    <AndroidGenerateResourceDesigner>false</AndroidGenerateResourceDesigner>
    <!-- https://github.com/dotnet/runtime/issues/90922 -->
    <NoWarn>$(NoWarn);CA2256</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'browser'">
    <DefineConstants>$(DefineConstants);BROWSER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Condition="'$(UseAvaloniaFork)' != 'True'" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.242" Condition="'$(UseAvaloniaFork)' == 'True'" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Avalonia.Controls.WebView" />
    <InternalsVisibleTo Include="Avalonia.Xpf.Controls.WebView" />
    <InternalsVisibleTo Include="Avalonia.Controls.WebView.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(AvaloniaPublicKey)' != ''">
    <InternalsVisibleTo Remove="Avalonia.Controls.WebView" />
    <InternalsVisibleTo Remove="Avalonia.Xpf.Controls.WebView" />
    <InternalsVisibleTo Remove="Avalonia.Controls.WebView.Tests" />
    <InternalsVisibleTo Include="Avalonia.Controls.WebView, PublicKey=$(AvaloniaPublicKey)" />
    <InternalsVisibleTo Include="Avalonia.Xpf.Controls.WebView, PublicKey=$(AvaloniaPublicKey)" />
    <InternalsVisibleTo Include="Avalonia.Controls.WebView.Tests, PublicKey=$(AvaloniaPublicKey)" />
  </ItemGroup>

  <Import Project="../Avalonia.Controls.WebView.Core/IncludeBuildItems.props" />
</Project>
